---
title: "Viz-BenT.rmd"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# https://docs.google.com/document/d/1PhTzUoqxsegEkrDOCC_Wc8z4rEJOSqo89PfFIPeifvk/preview#heading=h.ctpd18l06yte

library(broom)
library(dplyr)
library(ggplot2)
library(forcats)
library(readr)
library(rpart.plot)
library(tidymodels) 
library(varhandle)
library(vip)
library(here)

tidymodels_prefer()
conflicted::conflict_prefer("vi", "vip")

set.seed(123)

tickets_base <- read_csv(here("res/tickets.csv"))
```

```{r Data cleaning, include = FALSE}
tickets_mod <- tickets_base %>%
  select(-ticket, -ITOwner, -requestor) %>%
  rename(category = FiledAgainst) %>%
  rename(duration = daysOpen) %>%
  rename(impact = Severity) %>%
  rename(priority = Priority) %>%
  rename(satisfaction = Satisfaction) %>%
  rename(seniority = RequestorSeniority) %>%
  rename(type = TicketType) %>%
  mutate(category = replace(category, category == "Access/Login", "SSO/IAM")) %>%
  mutate(priority = replace(priority, priority == "0 - Unassigned", "Unclassified")) %>%
  mutate(priority = replace(priority, priority == "1 - Low", "Low")) %>%
  mutate(priority = replace(priority, priority == "2 - Medium", "Medium")) %>%
  mutate(priority = replace(priority, priority == "3 - High", "High")) %>%
  mutate(impact = replace(impact, impact == "0 - Unclassified", "Unclassified")) %>%
  mutate(impact = replace(impact, impact == "1 - Minor", "Single Person")) %>%
  mutate(impact = replace(impact, impact == "2 - Normal", "Group")) %>%
  mutate(impact = replace(impact, impact == "3 - Major", "Department")) %>%
  mutate(impact = replace(impact, impact == "4 - Critical", "Multiple Departments")) %>%
  mutate(satisfaction = replace(satisfaction, satisfaction == "0 - Unknown", "N/A")) %>%
  mutate(satisfaction = replace(satisfaction, satisfaction == "1 - Unsatisfied", "Unsatisfied")) %>%
  mutate(satisfaction = replace(satisfaction, satisfaction == "2 - Satisfied", "Satisfied")) %>%
  mutate(satisfaction = replace(satisfaction, satisfaction == "3 - Highly satisfied", "Highly Satisfied")) %>%
  mutate(seniority = replace(seniority, seniority == "1 - Junior", "Junior")) %>%
  mutate(seniority = replace(seniority, seniority == "2 - Regular", "Regular")) %>%
  mutate(seniority = replace(seniority, seniority == "3 - Senior", "Senior")) %>%
  mutate(seniority = replace(seniority, seniority == "4 - Management", "Management")) %>%
  mutate(type = replace(type, type == "Issue", "Malfunction")) 

# Implementation credit: Alex McCreight
tickets_mod2 <- tickets_mod %>% 
  mutate(wasEscalated = case_when(
    priority == "High" & impact == "Group" ~ 1,
    priority == "High" & impact == "Department" ~ 1,
    priority == "High" & impact == "Multiple Departments" ~ 1,
    TRUE ~ 0
  ))

str(tickets_mod2)

tickets <- as.data.frame(unclass(tickets_mod2), stringsAsFactors = TRUE)
tickets$wasEscalated <- as.factor(tickets$wasEscalated)
tickets$duration <- as.factor(tickets$duration)
```

```{r, echo = FALSE}
tickets_friendly <- tickets_mod2 %>%
  mutate(wasEscalated = recode(wasEscalated, "0" = "Not Escalated", "1" = "Escalated")) %>%
  mutate(impact = recode(impact, "Multiple Departments" = "Multiple Depts."))

tickets_friendly <- tickets_friendly %>%
  group_by(seniority) %>%
  mutate(senCount = n())

pdf("final_sen_viz.pdf",
    width = 10,
    height = 10)

ggplot(tickets_friendly) +
  geom_bar(aes(x = seniority, fill = category)) +
  facet_wrap(vars(wasEscalated)) + 
  labs(title = "Tickets by Escalation, Seniority, and Category", x = "Seniority", y = "Ticket Count", fill = "Category")

dev.off()

pdf("final_prio_viz.pdf",
    width = 10,
    height = 10)

ggplot(tickets_friendly) +
  geom_bar(aes(x = priority, fill = category)) +
  facet_wrap(vars(wasEscalated)) +
  labs(title = "Tickets by Escalation, Priority, and Category", x = "Priority", y = "Ticket Count", fill = "Category")

dev.off()

pdf("final_impact_viz.pdf",
    width = 10,
    height = 10)

ggplot(tickets_friendly) +
  geom_bar(aes(x = impact, fill = category)) +
  facet_wrap(vars(wasEscalated)) +
  scale_x_discrete(guide = guide_axis(n.dodge = 2)) + 
  labs(title = "Tickets by Escalation, Impact, and Category", x = "Priority", y = "Ticket Count", fill = "Category")

dev.off()

# Dooley
# Primary: Category vs ticket count
# Like that the bars are arranged in ascending order
ggplot(tickets_friendly) +
  geom_bar(aes(x = category, fill = seniority)) +
  facet_wrap(vars(wasEscalated))+
  labs( title="Correlation between category of ticket and  seniority of those filing it",
           subtitle="created by Dooley Kim",
           caption="This graph was created by Dooley Kim on 12-1-23. We could not find the source of this dataset unfortunately.")

# Sohail
# Primary: Priority vs ticket count
# Like the y-axis label
ggplot(tickets_mod2) +
  geom_bar(aes(x = priority, fill = seniority)) +
  facet_wrap(vars(wasEscalated)) + labs(x= "Priority", y= "Ticket Count" )+theme_classic()
```

